name: over_react_codemod
version: 2.37.1
homepage: https://github.com/Workiva/over_react_codemod

description: >
  Codemods for consumers of over_react that automate the migration of
  UI component code.


environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  analyzer: ^5.0.0
  args: ^2.2.0
  codemod: ^1.0.1
  collection: ^1.15.0
  glob: ^2.0.1
  json_annotation: ^4.8.0
  logging: ^1.0.1
  meta: ^1.16.0
  package_config: ^2.1.0
  path: ^1.8.0
  pub_semver: ^2.0.0
  source_span: ^1.8.1
  yaml: ^3.1.0
  yaml_edit: ^2.0.0
  file: ^6.1.2
  io: ^1.0.0
  w_transport: ^5.2.1

dev_dependencies:
  async: ^2.0.0
  build_runner: ^2.1.1
  build_test: ^2.1.3
  dart_dev: ^4.1.1
  dart_style: ^2.0.3
  dependency_validator: ^4.0.0
  json_serializable: ^6.5.3
  test: ^1.17.10
  test_descriptor: ^2.0.0
  uuid: ^4.0.0
  workiva_analysis_options: ^1.2.2

executables:
  dart2_9_upgrade:
  dependency_validator_ignore:
  null_safety_migrator_companion:
  null_safety_required_props:
  null_safety_prep:
  mui_migration:
  required_flux_props:
  rmui_preparation:
  rmui_bundle_update:
  intl_message_migration:
  sort_intl:
  unify_package_rename:
  react_18_upgrade:

dependency_overrides:
  dart_dev_workiva:
    git:
      url: https://github.com/Workiva/dart_dev_workiva.git
      ref: override-unify-ui-files-for-mui-v7
  unify_ui:
    git:
      url: https://github.com/Workiva/unify_ui.git
      ref: consumable_integration/mui/material-upgrade
