name: over_react_codemod
version: 1.6.0
homepage: https://github.com/Workiva/over_react_codemod

description: >
  Codemods for consumers of over_react that automate the migration of
  UI component code.

authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Corwin Sheahan <corwin.sheahan@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - George Lesica <george.lesica@workiva.com>
  - Greg Littlefield <greg.littlefield@workiva.com>
  - Joe Bingham <joe.bingham@workiva.com>
  - Keal Jones <keal.jones@workiva.com>
  - Sebastian Malysa <sebastian.malysa@workiva.com>
  - Sydney Jodon <sydney.jodon@workiva.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: '>=0.37.0 <0.39.0'
  args: ^1.5.1
  codemod: ^0.1.5
  collection: ^1.14.7
  logging: ^0.11.3+2
  meta: ^1.1.7
  path: ^1.6.2
  prompts: ^1.3.1
  pub_semver: ^1.4.2
  source_span: ^1.4.1
  yaml: ^2.1.16

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^1.0.0
  build_vm_compilers: ^1.0.0
  dart_dev: ^2.0.1
  dart_style: ^1.3.3
  dependency_validator: ^1.2.3
  mockito: ^4.0.0
  react: ^4.6.1
  test: ^1.5.1
  workiva_analysis_options: ^1.1.0

executables:
  boilerplate_upgrade:
  component2_upgrade:
  dart2_upgrade:
  react16_ci_precheck:
  react16_consumer_overlay_update:
  react16_dependency_override_update:
  react16_post_rollout_cleanup:
  react16_upgrade:
