name: over_react_codemod
version: 1.12.1
homepage: https://github.com/Workiva/over_react_codemod

description: >
  Codemods for consumers of over_react that automate the migration of
  UI component code.


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.7.2
  args: ^2.2.0
  codemod: ^1.0.1
  collection: ^1.15.0
  glob: ^2.0.1
  logging: ^1.0.1
  meta: ^1.7.0
  path: ^1.8.0
  prompts: ^2.0.0
  pub_semver: ^2.0.0
  source_span: ^1.8.1
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.1
  build_test: ^2.1.3
  dart_style: ^2.0.3
  dependency_validator: ^3.1.0
  mockito: ^5.0.14
  test: ^1.17.10
  test_descriptor: ^2.0.0
  workiva_analysis_options: ^1.2.2

executables:
  boilerplate_upgrade:
  component2_upgrade:
  dart2_upgrade:
  react16_ci_precheck:
  react16_consumer_overlay_update:
  react16_dependency_override_update:
  react16_post_rollout_cleanup:
  react16_upgrade:
  react17_dependency_override_update:
  react17_upgrade:
  dart2_9_upgrade:
